[package]
name = "gomoku"
version = "0.1.0"
edition = "2018"
default-run = "web"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
server = { path = "../web/server" }
core = { path = "../core" }
